Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
Service/Sources/Data/DataSource/Remote/DataSource/ImageRemote.swift
Service/Sources/Data/Repositories/DefaultImageRepository.swift
Service/Sources/Domain/Repositories/ImageRepository.swift

- ImageAPI
- ImageRemote
- ImageRepository

🔀 :: Image API 

---

Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
Service/Sources/Data/DataSource/Remote/DataSource/ImageRemote.swift
Service/Sources/Data/Repositories/DefaultImageRepository.swift
Service/Sources/Domain/Repositories/ImageRepository.swift
Service/Sources/Domain/UseCases/Club/CreateNewClubUseCase.swift
Service/Sources/Domain/UseCases/User/EditProfileUseCase.swift

🔀 :: Image API

---

Service/Sources/Domain/Entities/Club.swift
Service/Sources/Domain/Entities/ClubList.swift
Service/Sources/Domain/Entities/RelatedLink.swift
Service/Sources/Domain/Entities/User.swift
iOS/Sources/Presentation/Scene/Main/Accept/Reactor/AcceptReactor.swift
iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
iOS/Sources/Presentation/Scene/Main/MemberAppend/Reactor/MemberAppendReactor.swift
iOS/Sources/Presentation/Scene/Main/MyPage/Reactor/MyPageReactor.swift

Entity마다 static 변수로 Dummy Entity 설정후 사용

🔀 :: Dummy Entity 방식 변경

---

.package.resolved
ThirdPartyLib/Project.swift
Tuist/ProjectDescriptionHelpers/TargetDependency.swift
iOS/Sources/Application/DI/Container/AppDI.swift
iOS/Sources/Presentation/Scene/Main/Home/Items/EditorialClubListVC.swift
iOS/Sources/Presentation/Scene/Main/Home/Items/FreedomClubListVC.swift
iOS/Sources/Presentation/Scene/Main/Home/Items/MajorClubListVC.swift
iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift

기존 SegmentedControl로 동아리 종류를 검색하는 방식에서 Tab형식으로
ClubTypeSegmentedControl 삭제, Tabman적용하여 종류별 viewController 생성 및 HomeVC에 연결
SegmentedControl로 터치하여 종류 변경
Tabman으로 상단 탭 또는 SwipeGesture로 변경

🔀 :: HomeVC segmentedControl -> tabbar

---

iOS/Sources/Presentation/Scene/Login/VC/LoginVC.swift

passwordVisible 수정
passwordVisible 초기 설정 변경
passwordVisible 순서 변경
비밀번호가 먼저 열려있음
비밀번호가 닫혀있음
로그인 비밀번호 하기

✨ LoginVC passwordVisible

---

Service/Sources/DI/RepositoryAssembly.swift
Service/Sources/DI/UseCaseAssembly.swift
iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
iOS/Sources/Application/DI/Assembly/VCAssembly.swift
iOS/Sources/Presentation/Scene/Auth/Login/Reactor/LoginReactor.swift
iOS/Sources/Presentation/Scene/Auth/SignUp/Certification/VC/CertificationVC.swift

inject할때 inObjectScope가 String으로 reference라네요?
inject할때 weak로 resolve할때마다 initialize하게 로직 변경
💩

🔀 :: ARC 에러 해결

---

.package.resolved
Service/Sources/Data/DataSource/Remote/DataMapping/Club/DetailClub/DetailClubDTO.swift
Service/Sources/Data/DataSource/Remote/DataMapping/Club/DetailClub/DetailClubResponse.swift
Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
Service/Sources/Data/DataSource/Remote/Plugin/JWTPlugin.swift
ThirdPartyLib/Project.swift
Tuist/ProjectDescriptionHelpers/Excutable.swift
Tuist/ProjectDescriptionHelpers/TargetDependency.swift
iOS/Project.swift
iOS/Sources/Application/SceneDelegate.swift
iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
iOS/Sources/Presentation/Scene/Main/Home/Items/EditorialClubListVC.swift
iOS/Sources/Presentation/Scene/Main/Home/Items/FreedomClubListVC.swift
iOS/Sources/Presentation/Scene/Main/Home/Items/MajorClubListVC.swift
iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
iOS/Sources/Presentation/Scene/Main/MemberAppend/Reactor/MemberAppendReactor.swift
iOS/Sources/Presentation/Scene/Main/MyPage/VC/MyPageVC.swift

Inject 적용
오타사항이나 버그사항 해결(Auto refresh)

🔀 :: Inject적용 및 catch error

---

iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
iOS/Sources/Presentation/Scene/Main/NewClub/VC/SecondNewClubVC.swift

relatedLink가 nullable이였던 것이 not null이 되어서 변경
reactor에서 relatedLink를 not null
relatedLink type
relatedLink: RelatedLinkDTO? = nil
relatedLink: RelatedLinkDTO = ....

🔀 :: 관련 링크 정책 변경에 따라서 타입 변경

---

Service/Sources/DI/RepositoryAssembly.swift
Service/Sources/DI/UseCaseAssembly.swift
Service/Sources/Data/DataSource/Remote/API/AfterSchoolAPI.swift
Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
Service/Sources/Data/DataSource/Remote/DataMapping/AfterSchool/AfterSchoolDTO.swift
Service/Sources/Data/DataSource/Remote/DataMapping/AfterSchool/AfterSchoolList/AfterSchoolListResponse.swift
Service/Sources/Data/DataSource/Remote/DataMapping/Club/ClubList/ClubListDTO.swift
Service/Sources/Data/DataSource/Remote/DataSource/AfterSchoolRemote.swift
Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
Service/Sources/Data/Repositories/DefaultAfterSchoolRepository.swift
Service/Sources/Domain/Entities/AfterSchool.swift
Service/Sources/Domain/Entities/AfterSchoolQuery.swift
Service/Sources/Domain/Entities/AfterSchoolSeason.swift
Service/Sources/Domain/Entities/AfterSchoolWeek.swift
Service/Sources/Domain/Repositories/AfterSchoolRepository.swift
Service/Sources/Domain/UseCases/AfterSchool/ApplyAfterSchoolUseCase.swift
Service/Sources/Domain/UseCases/AfterSchool/CancelAfterSchoolUseCase.swift
Service/Sources/Domain/UseCases/AfterSchool/FetchAfterSchoolListUseCase.swift
Service/Sources/Domain/UseCases/AfterSchool/FetchFindAfterSchoolUseCase.swift

🔀 :: AfterSchoolAPI

---

iOS/Sources/Presentation/Scene/Auth/OnBoarding/Reactor/OnBoardingReactor.swift
iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift

🔀 :: GuestSignin feature

---

.package.resolved
Service/Sources/DI/UseCaseAssembly.swift
Service/Sources/Data/DataSource/Local/DataSource/ClubLocal.swift
Service/Sources/Data/DataSource/Local/Realm/Entity/ClubListRealmEntity.swift
Service/Sources/Data/DataSource/Local/Realm/RealmTask.swift
Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
Service/Sources/Data/DataSource/Remote/DataSource/ClubRemote.swift
Service/Sources/Data/Repositories/DefaultClubRepository.swift
Service/Sources/Data/Utils/Extension/Realm/Realm+Ext.swift
Service/Sources/Data/Utils/Extension/Realm/Results+Ext.swift
Service/Sources/Data/Utils/OfflineCache.swift
Service/Sources/Domain/Enums/OrderingType.swift
Service/Sources/Domain/Enums/QueryFilter.swift
Service/Sources/Domain/Repositories/ClubRepository.swift
Service/Sources/Domain/UseCases/Club/FetchGuestClubListUseCase.swift
Service/Sources/Domain/UseCases/Club/FetchGuestDetailClubUseCase.swift
ThirdPartyLib/Project.swift
Tuist/ProjectDescriptionHelpers/TargetDependency.swift
iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
iOS/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift

🔀 :: Feat/fetcher

---

Service/Sources/Data/DataSource/Remote/DataMapping/Club/DetailClub/DetailClubResponse.swift
Service/Sources/Domain/Entities/Club.swift
Service/Sources/Domain/UseCases/Image/UploadImagesUseCase.swift
iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
iOS/Sources/Presentation/Scene/Main/DetailClub/VC/DetailClubVC.swift
iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
iOS/Sources/Presentation/Scene/Main/UpdateClub/VC/SecondUpdateClubVC.swift

동아리 수정할때 일부 Property가 빈값으로 보내짐
initialState re binding

🔀 :: 동아리 수정할 때 빈 값을 보내는 오류 수정

---

Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
iOS/Sources/Presentation/Scene/Main/ClubMember/Reactor/ClubMemberReactor.swift
iOS/Sources/Presentation/Scene/Main/ClubMember/VC/ClubMemberVC.swift
iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/ApplicantCell.swift
iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/MemberHeaderView.swift
iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/StatusMemberCell.swift
iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
iOS/Sources/Presentation/Scene/Main/MyPage/VC/MyPageVC.swift

에러 처리 방식 변경
chevron animating 방법 변경

🔀 :: 동아리 멤버 바인딩

---

iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift
iOS/Sources/Presentation/Utils/Extensions/Swift/StringExt.swift

🔀 :: 동아리 생성/수정할때 제목에 정규식 적용

---

Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
Service/Sources/Data/DataSource/Remote/API/UserAPI.swift

API 요청 보낼 때 DELETE로 보낼 시 body가 안담기기 때문에 이를 전부 POST method로 변경
"
"

🔀 :: Request보낼 때 DELTE인 method를 POST로 변경

---

iOS/Sources/Presentation/Scene/Main/Home/VC/HomeVC.swift

mainVC bugfix
페이지를 넘어서 스크롤 되는거 막기
왼쪽 끝과 오른쪽 끝 페이지에서 스크롤 해보기

mainVC 리팩토링

---

Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
iOS/Sources/Presentation/Scene/Auth/OnBoarding/Reactor/OnBoardingReactor.swift
iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift

로그인 화면에 개인정보 처리방침, 사용자 이용 약관 추가
로그인 화면에 개인정보 처리방침, 사용자 이용 약관 추가
개인정보 처리방침, 사용자 이용 약관 버튼 누를시 노션 페이지로 이동
개인정보 처리방침, 사용자 이용 약관 버튼 누를시 노션 페이지로 이동
개인정보 처리방침, 사용자 이용 약관 버튼 눌러보기

🔀 :: feat/Privacy

---

iOS/Sources/Presentation/Scene/Auth/OnBoarding/VC/OnBoardingVC.swift

redesign onboardingVC
SignUp Label 지우기
SignUp Label 지우기
SignUp Label 지우기
로그인 페이지 확인

🔀 :: ReDesign OnboardingVC

---

Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
Service/Sources/Data/DataSource/Remote/API/GuestAPI.swift
Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
Service/Sources/Domain/Error/GCMSError.swift
iOS/Sources/Presentation/Scene/Main/ClubMember/Reactor/ClubMemberReactor.swift
iOS/Sources/Presentation/Scene/Main/DetailClub/Reactor/DetailClubReactor.swift
iOS/Sources/Presentation/Scene/Main/NewClub/Reactor/NewClubReactor.swift
iOS/Sources/Presentation/Scene/Main/UpdateClub/Reactor/UpadteClubReactor.swift

error Mapping
error Mapping하였습니다
error Mapping 만들기
에러 띄워보기

🔀 :: feat/errorMapping

---

iOS/Sources/Presentation/Scene/Main/MemberAppend/VC/MemberAppendVC.swift

🔀 :: redesign 멤버 리스트

---

Service/Sources/DI/UseCaseAssembly.swift
Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
Service/Sources/Data/DataSource/Remote/API/GuestAPI.swift
Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
Service/Sources/Data/DataSource/Remote/DataMapping/Club/Member/MemberDTO.swift
Service/Sources/Data/DataSource/Remote/DataSource/ClubMemberRemote.swift
Service/Sources/Data/DataSource/Remote/DataSource/ClubRemote.swift
Service/Sources/Data/Repositories/DefaultClubMemberRepository.swift
Service/Sources/Data/Repositories/DefaultClubRepository.swift
Service/Sources/Domain/Entities/Member.swift
Service/Sources/Domain/Error/ClubMemberError.swift
Service/Sources/Domain/Repositories/ClubMemberRepository.swift
Service/Sources/Domain/Repositories/ClubRepository.swift
Service/Sources/Domain/UseCases/Club/ClubDelegationUseCase.swift
Service/Sources/Domain/UseCases/Club/FetchClubMemberUseCase.swift
Service/Sources/Domain/UseCases/Club/UserKickUseCase.swift
iOS/Sources/Presentation/Scene/Main/ClubMember/ClubMemberReactor.swift
iOS/Sources/Presentation/Scene/Main/ClubMember/View/Cell/StatusMemberCell.swift

clubmember API를 API 명세서에 맞게 변경하였습니다.
- clubAPI, clubMemberAPI 분리
- ClubMemberError 추가
- ClubRemote, ClubMemberRemote 분리
- ClubRepository, ClubMemberRepository 분리
- add DefaultClubMemberRepository

🔀:: clubMember-api-change

---

Service/Sources/Data/DataSource/Local/Keychain/KeychainLocal.swift
Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
Service/Sources/Data/DataSource/Remote/DataMapping/Token/TokenDTO.swift
Service/Sources/Data/DataSource/Remote/DataSource/AuthRemote.swift
Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
Service/Sources/Data/DataSource/Remote/Plugin/JWTPlugin.swift
Service/Sources/Data/Repositories/DefaultAuthRepository.swift
Service/Sources/Data/Utils/DateUtil.swift
Service/Sources/Domain/Repositories/AuthRepository.swift
Service/Sources/Domain/UseCases/Auth/LoginUseCase.swift
ThirdPartyLib/Project.swift
Tuist/Dependencies.swift
Tuist/ProjectDescriptionHelpers/TargetDependency.swift
iOS/Sources/Presentation/Scene/Auth/OnBoarding/OnBoardingReactor.swift
iOS/Sources/Presentation/Scene/Auth/OnBoarding/OnBoardingVC.swift

GAuth로 로그인 변경
GAuth로 로그인 변경함
TokenDTO expiredAt -> accessExp, refreshExp 추가됨
login(idToken: String) -> logint(code: String) 변경됨
GAuth 버튼 눌러서 사용

🔀 :: GAuth로 로그인 변경

---

.package.resolved
Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
Service/Sources/Data/DataSource/Remote/API/ClubAPI.swift
Service/Sources/Data/DataSource/Remote/API/ClubApplicantAPI.swift
Service/Sources/Data/DataSource/Remote/API/ClubMemberAPI.swift
Service/Sources/Data/DataSource/Remote/API/GCMSAPI.swift
Service/Sources/Data/DataSource/Remote/API/ImageAPI.swift
Service/Sources/Data/DataSource/Remote/API/UserAPI.swift
Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
Service/Sources/Domain/Error/ClubApplicantError.swift
Service/Sources/Domain/Error/ClubMemberError.swift
Service/Sources/Domain/Error/GCMSError.swift
iOS/Sources/Presentation/Scene/Auth/OnBoarding/OnBoardingReactor.swift
iOS/Sources/Presentation/Scene/Main/ClubMember/ClubMemberReactor.swift
iOS/Sources/Presentation/Scene/Main/DetailClub/DetailClubReactor.swift
iOS/Sources/Presentation/Scene/Main/MyPage/MyPageReactor.swift
iOS/Sources/Presentation/Scene/Main/MyPage/MyPageVC.swift
iOS/Sources/Presentation/Scene/Main/NewClub/NewClubReactor.swift
iOS/Sources/Presentation/Scene/Main/Update/UpdateClubReactor.swift
iOS/Sources/Presentation/Utils/Extensions/Swift/ErrorExt.swift

API에 맞게 statusCode Error를 추가했습니다.
- ImageAPI를 API에 맞게 statusCode Error 추가
- UserAPI를 API에 맞게 statusCode Error 추가
- AuthAPI를 API에 맞게 statusCode Error 추가

🔀:: api-error-add

---

Service/Sources/Data/DataSource/Local/Realm/RealmTask.swift

마이그레이션을 안해 앱이 죽는 현상 발생
Local Entity의 컬럼이 바뀜에 따라 migration을 실시
데이터베이스 마이그레이션

🔀 :: Realm 데이터베이스 마이그레이션

---

iOS/Sources/Presentation/Scene/Main/NewClub/NewClubReactor.swift
iOS/Sources/Presentation/Scene/Main/Update/UpdateClubReactor.swift
iOS/Sources/Presentation/Utils/Extensions/Swift/StringExt.swift

textField 공백이랑 enter 체크
textField 공백이랑 enter 체크하게 바꿈
🎸

🔀 :: textField 공백이랑 enter 체크

---

Service/Sources/Data/DataSource/Remote/API/AuthAPI.swift
Service/Sources/Domain/Error/GCMSError.swift
iOS/Sources/Presentation/Scene/Main/Update/UpdateClubReactor.swift

리프레시를 백에서 다중로그인으로 수정하여 일이 사라짐
에러 메세지 수정 및 refresh 401 에러 추가

🔀 :: 어떨결에 에러 메세지만 바꿈

---

iOS/Sources/Presentation/Scene/Main/DetailClub/DetailClubVC.swift
iOS/Sources/Presentation/Utils/Extensions/UIKit/UIView/UIViewExt.swift

🔀 :: bannerImage에 gradient 추가

---

.package.resolved
Service/Sources/DI/UseCaseAssembly.swift
Service/Sources/Domain/UseCases/User/FetchMiniProfileUseCase.swift
iOS/Sources/Application/DI/Assembly/ReactorAssembly.swift
iOS/Sources/Presentation/Scene/Main/Home/HomeReactor.swift
iOS/Sources/Presentation/Scene/Main/Home/HomeVC.swift

마이페이지버튼 마이프로필이미지로 변경
마이페이지버튼 마이프로필이미지로 변경

🔀 :: 마이페이지버튼 마이프로필이미지로 변경

---

Service/Sources/DI/DataSourceAssembly.swift
Service/Sources/DI/RepositoryAssembly.swift
Service/Sources/Data/DataSource/Local/DataSource/ClubLocal.swift
Service/Sources/Data/DataSource/Local/Keychain/KeychainLocal.swift
Service/Sources/Data/DataSource/Local/Realm/RealmTask.swift
Service/Sources/Data/DataSource/Remote/DataSource/AuthRemote.swift
Service/Sources/Data/DataSource/Remote/DataSource/BaseRemote.swift
Service/Sources/Data/DataSource/Remote/DataSource/ClubApplicantRemote.swift
Service/Sources/Data/DataSource/Remote/DataSource/ClubMemberRemote.swift
Service/Sources/Data/DataSource/Remote/DataSource/ClubRemote.swift
Service/Sources/Data/DataSource/Remote/DataSource/ImageRemote.swift
Service/Sources/Data/DataSource/Remote/DataSource/UserRemote.swift
Service/Sources/Data/DataSource/Remote/Plugin/JWTPlugin.swift
Service/Sources/Data/Repositories/DefaultAuthRepository.swift
Service/Sources/Data/Repositories/DefaultClubApplicantRepository.swift
Service/Sources/Data/Repositories/DefaultClubMemberRepository.swift
Service/Sources/Data/Repositories/DefaultClubRepository.swift
Service/Sources/Data/Repositories/DefaultImageRepository.swift
Service/Sources/Data/Repositories/DefaultUserRepository.swift
iOS/Sources/Application/AppDelegate.swift

DataSource들이 싱글톤으로 이루어져 있어 테스트를 할 수 없었던 것을 DI패턴으로 바꿔서, 테스트를 가능하게 만들었습니다.

🔀 :: 싱글톤으로 덕지덕지 이루어져있던 DataSource들을 DI 패턴으로 바꿉니다
